// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/4/2024, 1:43:52 PM
const configMerger = require("C:/Users/Phong/Desktop/Materials/astirz.github.io/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Phong/Desktop/Materials/astirz.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/plugins/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/astirz.github.io/composables/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/astirz.github.io/utils/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/astirz.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/astirz.github.io/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/Phong/Desktop/Materials/astirz.github.io/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
