// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/24/2024, 1:27:47 PM
const configMerger = require("C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/plugins/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/composables/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/utils/**/*.{js,ts,mjs}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["11"] = "C:/Users/Phong/Desktop/Materials/repo/nuxt-blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
